server:
  port: 9090
spring:
  datasource:
    username: root
    password: burak2424
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example_db?useSSL=false&AllowPublicKeyRetrieval=true&serverTimezone=UTC
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
  jpa:
    hibernate:
      ddl-auto: update
